
version: '3'

services:
  php:
    build: ./images/php
    volumes:
      - ../project:/var/www/html
    depends_on: 
      - postgres

  nginx: 
    image: nginx:stable-alpine
    volumes:
      - ../project:/var/www/html
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT:-80:80}

  postgres:
    image: postgres:16.0-alpine
    restart: "always"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres} 
    ports: 
      - ${POSTGRES_PORT:-5432:5432}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - ${ADMINER_PORT:-8080:8080}
volumes:
  postgres_data: