version: '3'

services:
  php:
    build: ./images/php
    depends_on: 
      - postgres

  nginx: 
    image: nginx:stable-alpine
    ports:
      - ${NGINX_PORT:-80:80}

  postgres:
    image: postgres:16.0-alpine
    restart: "always"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres} 
    ports: 
      - ${POSTGRES_PORT:-5432:5432}
    volumes:  
      - postgres_data:/var/lib/postgressql/data    
  
  volumes:
    postgres_data: